### ISSUE TITLE
Benchmarks with `concat()`?

### ISSUE THREAD

**Issue by nisbet-hubbard** [cloudflare/wildcard#10]
You wrote in the accompanying blogpost that you’re limiting the capturing wildcards to 8 so the difference may not be significant. But since the old `concat()` function remains available, I’m wondering how the two compares in terms of performance.

**Comment by orium** [comment]
This crate only provides wildcard matching, it doesn't know anything about the rules engine (which `concat()` is a part of). Also, there's no limits on captures or metacharacters in this crate: that's all enforced by the rules engine.
